### ISSUE TITLE
focal support needs to be added to fail check

### ISSUE THREAD

**Issue by acidprime** [voxpupuli/puppet-monit#20]
Overriding this on focal seems to work fine e.g. `FACTER_lsbdistcodename=bionic puppet agent -t` I can submit a PR but I actually think this fail code is maybe too heavy handed, given it needs to be updated every dist. It would be nice if there was a param to turn off the check or if the dists were added as they come out.

Great module though, thanks!

**Comment by acidprime** [comment]
I am testing this in my fork https://github.com/acidprime/puppet-monit/pull/1/files

**Comment by floSoX** [comment]
Hi,
Please, create a PR, and if you can, update tests with this new dist.
Thanks you for your suggestion. I have no time now to transform this part of code but you can create an issue, or better a PR, to change this.
Regards,

**Comment by maxadamo** [comment]
@FlorentPoinsaut the PR was created, the test was added as per your request. 
It took eleven months to add one string. and it's not yet in place. 
Do you need some help to handle this repository? Have you considered handing the repository over vox-pupuli?

**Comment by FlorentPoinsaut** [comment]
Hi @maxadamo!
You are right. I don't take the time to maintain this repo properly. So yes, I need help. :-)
vox-pupuli seems to be a good way but I never took the time to do the transfer. :-s

**Comment by maxadamo** [comment]
@FlorentPoinsaut I have just spoken to @bastelfreak from #voxpupuli. 
They don't have any objection, but they've already committed to a lot of projects and they need to appoint someone, to share the load of the PRs with you, and you maintain the merge access on the project. 
He proposed my name and I gave my availability. If it's something you like, I can go through the documentation, to initiate the migration process. 

If you have an inquiry regarding voxpupuli, the whole process, I think Tim (@bastelfreak) is the right person to ask. 
cheers

**Comment by FlorentPoinsaut** [comment]
Hi @maxadamo!
Great! Go ahead! Tell me if you need anything.
Regards,

**Comment by bastelfreak** [comment]
hey @FlorentPoinsaut , I sent you a GitHub invitation to the Vox Pupuli namespace. If you accept that you get the permissions to migrate the repository into our namespace. Please take a look at the migration guide at https://voxpupuli.org/docs/migrate_module/ . Let me know if anything is unclear.
@maxadamo I granted you collaborator status at Vox Pupuli so you're able to work on monit once its migrated.

**Comment by FlorentPoinsaut** [comment]
HI @bastelfreak!
Thanks a lot. I have accept your invitation and I will follow the migration guide as soon as possible.

**Comment by FlorentPoinsaut** [comment]
@bastelfreak, I give you back the control for these next actions:
> - Ask an admin to add the collaborators team to the module’s Collaborators & Teams ‘Teams’ list with Write permissions (e.g. https://github.com/voxpupuli/puppet-gitlab/settings/collaboration (that link works only for admins).
>- The admin shall also update the access permissions (that link works only for admins) for forge.puppet.com secrets so releases can be published.
>- The admin shall also enable Automatically delete head branches in the repository settings.

:-)

**Comment by zilchms** [comment]
I will be closing this, as voxpupuli has taken over :) btw: ubuntu 20.04 (focal) support was added in #53
