### ISSUE TITLE
Support latest puppet version (7.x)

### ISSUE THREAD

**Issue by siebrand** [voxpupuli/puppet-monit#26]
Currently metadata.json states that puppet up to and including version 5 is supported. Puppet 5.5 went EOL January 2021.

**Comment by Helkar** [comment]
@bastelfreak I saw that the metadata.json was updated to drop puppet 6 support but I don't think the puppet firewall module version set there does support puppet 7 though. is there any ETA on when this module will be fully adapted? Thanks

**Comment by zilchms** [comment]
I am currently working on getting this working with recent modules and puppet versions. However, I cannot guarantee I get it fixed soon as the dependencies are quite old.

**Comment by zilchms** [comment]
Got it all working now. #50 and #51 fix the firewall dependencies. #28 fixes stdlib stuff. And #29 adds puppet 8 support. And a new release to forge is coming, too, as soon as I get to it :)
